# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mini_daq_conn.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mini_daq_connection(object):
    def setupUi(self, mini_daq_connection):
        mini_daq_connection.setObjectName("mini_daq_connection")
        mini_daq_connection.resize(309, 89)
        self.verticalLayout = QtWidgets.QVBoxLayout(mini_daq_connection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ip_lbl = QtWidgets.QLabel(mini_daq_connection)
        self.ip_lbl.setObjectName("ip_lbl")
        self.horizontalLayout.addWidget(self.ip_lbl)
        self.ip_lineedit = QtWidgets.QLineEdit(mini_daq_connection)
        self.ip_lineedit.setObjectName("ip_lineedit")
        self.horizontalLayout.addWidget(self.ip_lineedit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_daq_connect = QtWidgets.QPushButton(mini_daq_connection)
        self.pb_daq_connect.setObjectName("pb_daq_connect")
        self.horizontalLayout_2.addWidget(self.pb_daq_connect)
        self.pb_conn_details = QtWidgets.QPushButton(mini_daq_connection)
        self.pb_conn_details.setObjectName("pb_conn_details")
        self.horizontalLayout_2.addWidget(self.pb_conn_details)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(mini_daq_connection)
        QtCore.QMetaObject.connectSlotsByName(mini_daq_connection)

    def retranslateUi(self, mini_daq_connection):
        _translate = QtCore.QCoreApplication.translate
        mini_daq_connection.setWindowTitle(_translate("mini_daq_connection", "Form"))
        self.ip_lbl.setText(_translate("mini_daq_connection", "IP"))
        self.pb_daq_connect.setText(_translate("mini_daq_connection", "Connect"))
        self.pb_conn_details.setText(_translate("mini_daq_connection", "Connection details"))
