# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\modpiratsinout_big.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModulePiratsInOutBig(object):
    def setupUi(self, ModulePiratsInOutBig):
        ModulePiratsInOutBig.setObjectName("ModulePiratsInOutBig")
        ModulePiratsInOutBig.resize(1064, 730)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(ModulePiratsInOutBig)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(ModulePiratsInOutBig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.outputs_gridLayout = QtWidgets.QGridLayout()
        self.outputs_gridLayout.setObjectName("outputs_gridLayout")
        self.horizontalLayout.addLayout(self.outputs_gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_11.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(ModulePiratsInOutBig)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_11.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(ModulePiratsInOutBig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.inputs_gridLayout = QtWidgets.QGridLayout()
        self.inputs_gridLayout.setObjectName("inputs_gridLayout")
        self.horizontalLayout_2.addLayout(self.inputs_gridLayout)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_11.addLayout(self.verticalLayout_2)

        self.retranslateUi(ModulePiratsInOutBig)
        QtCore.QMetaObject.connectSlotsByName(ModulePiratsInOutBig)

    def retranslateUi(self, ModulePiratsInOutBig):
        _translate = QtCore.QCoreApplication.translate
        ModulePiratsInOutBig.setWindowTitle(_translate("ModulePiratsInOutBig", "Pirats Ins And Outs Module"))
        self.label_2.setText(_translate("ModulePiratsInOutBig", "Outputs Control"))
        self.label_3.setText(_translate("ModulePiratsInOutBig", "Inputs Reading"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModulePiratsInOutBig = QtWidgets.QWidget()
    ui = Ui_ModulePiratsInOutBig()
    ui.setupUi(ModulePiratsInOutBig)
    ModulePiratsInOutBig.show()
    sys.exit(app.exec_())
